name: Second Workflow
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the Environment'
        required: true
        default: 'warning'
        type: choice
        options:
        - Test
        - Stage
        - Prod
  push: 
    branches:
      -main
 
    
     
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v3
