name: Second Workflow
on: 
  push:
    branches:
      - main
      - test
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        run: echo "Deploying..."
